version: '2'
services:
  petclinic-rest:
    image: 957582603404.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic-rest:latest
    cpu_shares: 100
    mem_reservation: 512000000
    ports:
      - "0:9460"
    logging:
      driver: awslogs
      options:
        awslogs-group: petclinic-rest
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: petclinic