version: '2'
services:
  petclinic-rest:
    image: 957582603404.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic-rest:latest
    mem_limit: 1024m
    mem_reservation: 512m
    ports:
      - "0:9460"
    logging:
      driver: awslogs
      options:
        awslogs-group: petclinic-rest
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: petclinic