spring:
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 9460

petclinic:
  name: AK 한방병원
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]

